GH-10: PHP8 compatibility.
drupaltest/behat_traits pull request #11
Opened 2022-01-31 16:13 UTC by nagyad

Banched out of GH-6.

2022-01-31 17:11 UTC, sergepavle requested changes

2022-01-31 17:11 UTC, sergepavle commented on docker-compose.yml
>        XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
```suggestion
      COMPOSERVER: "--2"
      XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
```

2022-01-31 17:11 UTC, sergepavle commented on composer.json
>      "autoload": {
Missed `allow-plugins`

2022-02-01 10:41 UTC, hernani commented on docker-compose.yml
>        XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
The XDEBUG_CONFIG seems old

2022-02-01 13:01 UTC, nagyad commented
Closing in favor of: https://github.com/drupaltest/behat-traits/pull/12

2022-02-01 13:01 UTC, closed without merging

2022-02-03 11:48 UTC, 22Alexandra commented on README.md
> +* [PHP 8.0](http://php.net/)
We still support 7.4.