GH-6: Drupal 9 dependencies.
drupaltest/behat_traits pull request #7
Opened 2021-05-11 10:51 UTC by upchuk

2021-05-13 07:10 UTC, pfrenssen requested changes

2021-05-13 07:10 UTC, pfrenssen commented on composer.json
> +        "drupal/core": "^8.9 || ^9",
We should aim to keep the minimum required versions of PHP and core unchanged, this breaks backwards compatibility for existing projects. It should be possible to introduce Drupal 9 compatibility while still retaining full compatibility with 8.6 and PHP 7.1.

2021-05-13 07:10 UTC, pfrenssen commented on composer.json
> +        "openeuropa/task-runner": "^1.0.0-beta6",
Let's not introduce the code review tool from OpenEuropa here. This is meant to be a project which is usable by the entire Drupal community. This organisation is owned by Jonathan Hedstrom, not by us. The OpenEuropa rules include checks which don't make sense for the wider Drupal community.

2021-05-13 07:10 UTC, pfrenssen commented on docker-compose.yml
> +    image: fpfis/httpd-php-dev:7.3
This is not a good approach. We should have a test matrix that allows to test the range of supported versions, all the way from Drupal 8.6 on PHP 7.1 to Drupal 9.1 on PHP 7.4.

2021-07-22 12:38 UTC, abel-santos-corral commented on docker-compose.yml
> +    image: fpfis/httpd-php-dev:7.3
@pfrenssen we have implemented the changes for the feedback asked, but it has been implemented in https://github.com/drupaltest/behat-traits/pull/8 but we dont have perissions to add commits so we forked. We don't have permissions, could you please check and merge if all is ok. Thanks in advance.

2022-02-02 23:16 UTC, merged